kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    pull: always
    image: golang:1.13
    commands:
      - make build
    environment:
      CGO_ENABLED: 0
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org

  - name: configuration
    pull: always
    image: golang:1.13
    commands:
      - go get github.com/google/go-jsonnet/cmd/jsonnet
      - go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
      - go get github.com/brancz/gojsontoyaml
      - jb install
      - make kubernetes.yaml
    environment:
      CGO_ENABLED: 0
      GO111MODULE: off
      GOPROXY: https://proxy.golang.org

  - name: container
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/metalmatze/slo-libsonnet-web
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      auto_tag: true
    when:
      branch:
        - master
        - drone
      event:
        - push
