kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: build-go
    pull: always
    image: golang:1.14
    commands:
      - make promtools.dev
    environment:
      CGO_ENABLED: 0
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org

  - name: build-ui
    pull: always
    image: node:16.5
    commands:
      - npm run build

  - name: configuration
    pull: always
    image: golang:1.14
    commands:
      - go get github.com/google/go-jsonnet/cmd/jsonnet
      - go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
      - go get github.com/brancz/gojsontoyaml
      - jb install
      - make kubernetes.yaml
    environment:
      CGO_ENABLED: 0
      GO111MODULE: off
      GOPROXY: https://proxy.golang.org

  - name: container
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/metalmatze/slo-libsonnet-web
      tag:
        - ${DRONE_COMMIT_SHA:0:7}
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
    when:
      branch:
        - master
      event:
        - push

  - name: container-configuration
    image: plugins/docker
    settings:
      dockerfile: Dockerfile.configuration
      registry: quay.io
      repo: quay.io/metalmatze/slo-libsonnet-web
      tag:
        - ${DRONE_COMMIT_SHA:0:7}-configuration
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
    when:
      branch:
        - master
      event:
        - push

  - name: deploy
    pull: always
    image: quay.io/signalcd/drone
    environment:
      PLUGIN_API_URL:
        from_secret: signalcd_api
      PLUGIN_BASICAUTH_USERNAME:
        from_secret: signalcd_username
      PLUGIN_BASICAUTH_PASSWORD:
        from_secret: signalcd_password
    when:
      branch:
        - master
      event:
        - push
